spring:
  application:
    name: remember-everything-app
  messages:
    fallback-to-system-locale: off
    encoding: UTF-8
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

jwt:
  secret: some-secret
  expiration: 86400 # milliseconds
  clock-skew: 30 # secondes
